platform :ios, '5.0'
pod 'JSONKit',       '~> 1.4'
pod 'RestKit',       '~> 0.20.0pre6'
pod 'MBProgressHUD', '~> 0.5'
pod 'SDWebImage',    '~> 3.1'
pod 'WEPopover',     '~> 0.0.1'
pod 'Mixpanel',      '~> 1.1.1'
pod 'Parse',         '~> 1.2.0'
pod 'Facebook-iOS-SDK', '~> 3.2.0'
pod 'TestFlightSDK', '~> 1.3.0.beta2'